// view1/src/App.jsx
import React, { Component } from 'react';
import { BrowserRouter as Router } from 'react-router-dom';
import Topbar from './components/common/Topbar';

class App extends Component {
  render() {
    return (
      <Router>
        <div className="App">
          <Topbar></Topbar>
        </div>
      </Router>
    );
  }
}

export default App;

// view/src/App.vue
<template>
  <div id="app">
    <topbar></topbar>
    <router-view class="wrapper" />
    <toast></toast>
  </div>
</template>

<script>
import Topbar from '@/components/common/topbar/Topbar'
import Toast from '@/components/common/Toast'

export default {
  name: 'App',
  components: {Topbar, Toast}
}
</script>

<style lang="scss">
  @import './assets/style/app-reset.scss';
  @import './assets/style/common.scss';
  @import '../node_modules/flex.css/dist/flex.css';
</style>
