// views/src/App.vue
<template>
  <div id="app" class="w-1000" flex="dir:left">
    <side-bar></side-bar>
    <router-view flex-box="1" />
  </div>
</template>

<script>
  import SideBar from './components/common/SideBar'
  
  export default {
    name: 'App',
    components: {
      SideBar
    }
  }
</script>

<style lang="scss">
  @import './assets/style/app-reset.scss';
  @import './assets/style/common.scss';
  @import '../node_modules/flex.css/dist/flex.css';
</style>

// view2/src/App.jsx
import React, {Component} from 'react';
import { BrowserRouter as Router, Route } from 'react-router-dom';
import Sidebar from './components/common/Sidebar/Sidebar';
import Index from './components/index/Index';

class App extends Component {
  render() {
    return (
      <Router>
        <div className="wrapper" data-flex="dir:left">
          <Sidebar></Sidebar>
          <div className="main p-t-40" data-flex-box="1">
            <Route path="/" component={Index} />
          </div>
        </div>
      </Router>
    );
  }
}

export default App;
